set global indentwidth 4
map global insert <tab> '    '
map global insert <backtab> '<a-;><lt>'
map global normal <c-p> ':find '
map global user w '%s +$<ret>d '

# Fuzzy file finder
def find -allow-override -params 1 -shell-candidates %{
    find \( -name venv -o -name node_modules -o -name build  -o -name .hg -o -name .git \) -prune -o \
         -type f ! -name '*.pyc' -print
} %{ edit %arg{1} }

# Faster grep
set global grepcmd "%sh{
    AG=$(command -v ag)
    ACK=${AG:-$(command -v ack)}
    echo ${ACK:-grep -RHn}
}"

# Python files
hook -group custom global BufCreate .*\.py %{
    set buffer lintcmd flake8
    map buffer normal <a-\> '<a-i>wy:tag <c-r>"<ret>'
    map buffer user l ':lint<ret>:b *lint-output*<ret>'
}

hook -group custom global BufCreate .*\.js %{
    set buffer lintcmd jshint
    map buffer normal <a-\> '<a-i>wy:tag <c-r>"<ret>'
    map buffer user l ':lint<ret>:b *lint-output*<ret>'
}

hook -group custom global BufCreate .*\.jinja2 %{
    set buffer filetype html
}
